### ISSUE TITLE
json vpn section fails on usg 

### ISSUE THREAD

**Issue by p1eterdeboer** [coolhva/usg-kpn-ftth#1]
When using the config.gateway.json on my USB (Model: UniFi-Gateway-3, Version:     4.4.44.5213844) the VPN section results in a commit failure causing a boot loop.
Message: 
[commit error] VPN Warning: IPSec configured but no site-to-site peers or l2tp remote-users configured

Removing this section solves the problem and results in (so far) stable IPTV and internet.

**Comment by coolhva** [comment]
Fixed by removing the VPN section as it is probably not used by many and if you use it you know how to adjust the json.
