### ISSUE TITLE
Hangs on 85% error code 561

### ISSUE THREAD

**Issue by TechWizard80** [coolhva/usg-kpn-ftth#10]
I used you config and when I want to start the IPTV decoder I get an error. At 85% it stops loading and I get the error code 561. Any idea what this can be?

**Comment by coolhva** [comment]
Did you look at the troubleshooting topic at tweakers? https://gathering.tweakers.net/forum/list_message/60188896#60188896

Probably the route to the IPTV network is not present, can you go through the troubleshooting steps and see if you have an interface eth0.4, an ip address assigned to it, the static route to the KPN network, etc.?

**Comment by TechWizard80** [comment]
Ok, once I get a chance to try again, I will let you know.
Although I did already look in to that, and everything seemed to be fine concerning routes. That is why I don't understand why it isn't working and don't understand that no one else is having the same issue.
Anyway, I will check again.

**Comment by TechWizard80** [comment]
> Did you look at the troubleshooting topic at tweakers? https://gathering.tweakers.net/forum/list_message/60188896#60188896
> 
> Probably the route to the IPTV network is not present, can you go through the troubleshooting steps and see if you have an interface eth0.4, an ip address assigned to it, the static route to the KPN network, etc.?

Why is it closed? I haven't had a chance to look into the routing yet. I was about to do it today or tomorrow.

**Comment by coolhva** [comment]
Sorry, I misread your post. Please let me know if I can help (or have a live remote troubleshooting session).

**Comment by coolhva** [comment]
Do you have an update on the issue; If I can help please let me know.

**Comment by TechWizard80** [comment]
Router config is correct... Still don't understand why it's not working.
Need to troubleshoot some more.



Op ma 30 dec. 2019 12:50 schreef Henk van Achterberg <
notifications@github.com>:

**Comment by jo-her** [comment]
I had the same error. Placed a file rfc3442-classless-routes (from internet) in /etc/dhcp3/dhclient-exit-hooks.d  Chmod +x /etc/dhcp3/dhclient-exit-hooks.d/rfc3442-classless-routes
After een reboot no error code 561. IPTV is up-and-running.
But show interfaces diplayed no ipv6 adres for eth1. Does dhcp6 running?

**Comment by jo-her** [comment]
Copying en chmod under sudo su

**Comment by jo-her** [comment]
I removed routes out of /etc/dhcp3/dhclient-exit-hooks.d
shutdown -r now
after the reboot a new routes file was present and IPTV was still active 
I removed rfc3442-classes-routes
renew dhcp interface eth0.4 and powered off and on de STB. After that: TV
shutdown -r now
After that: YES, IPTV.

**Comment by coolhva** [comment]
@TechWizard80 did you download the files from the repo or did you copy and paste the contents? The latter will create this error. please download the repo zip and copy the files via winscp.

**Comment by jo-her** [comment]
i copy and paste the contest in notepad++. Afterthat ik used winscp.
I'll try the zip-file now.

**Comment by jo-her** [comment]
Better. I see the IPV6 address for eth1 at once. For de kernel route (iptv) a second reboot: then ok

**Comment by TechWizard80** [comment]
No... Still not working.

I did see that the tv was working after following the instructions, but when I switched the decoder on the back of the device off and then on, I again get the error

**Comment by jo-her** [comment]
After USG provision the first time de (K) route is not always present (show ip route). Turn off en on the USG. Give it a try.

**Comment by TechWizard80** [comment]
I did a reboot even before you commented, you are right, it's working now... Thank you all.
