### ISSUE TITLE
Controller shows DHCP on WAN 1

### ISSUE THREAD

**Issue by eliosfederico** [coolhva/usg-kpn-ftth#11]
I see from the controller screenshot that also to you, @coolhva, the WAN 1 will go to DHCP when using this config? Is this a controller bug?

**Comment by coolhva** [comment]
This is not a bug but the interface can't handle the advanced configuration with two networks at the WAN side. So this is a shortcoming of the GUI and hopefully Ubiquity will fix this in the future.
