### ISSUE TITLE
Cannot manage to get IPV6 working

### ISSUE THREAD

**Issue by eliosfederico** [coolhva/usg-kpn-ftth#12]
Hi, everythings seems to work fine on my USG 4P but no luck with IPV6.

With `show interfaces` I see an address on my LAN interface and with `show interfaces pppoe pppoe2 log | match "IPV6|LL"` I can see the local and remote address. Also my windows computer is getting a IPV6 IP but I can't PING any IPV6 address and the ipv6test fails.

What am I doing wrong?

![kk](https://user-images.githubusercontent.com/725955/72727084-57a24780-3b8a-11ea-9bc5-994e0cd8aa87.JPG)

**Comment by coolhva** [comment]
You are not doing anything wrong, I think this problem lies with your client. Do you have a phone or laptop or any other device which supports ipv6 which you can test with?

**Comment by eliosfederico** [comment]
I tried with a Windows laptop, iPhone and Android all with the same result. I use the UniFi Switch 8 and 16.

**Comment by eliosfederico** [comment]
This is what happens if I try to ping the IPV6 DNS of Cloudlfare from the USG
![ping](https://user-images.githubusercontent.com/725955/72737304-9db5d600-3b9f-11ea-9a72-4d7b58638113.JPG)

On a Windows machine I get just that the request has timed out. 
Anything else I can test?

**Comment by coolhva** [comment]
you can see what your ipv6 address is on your windows machine (ipconfig /all) and what the route table for ipv6 is (route print -6), can you ping your ipv6 default gateway?

**Comment by eliosfederico** [comment]
To begin with: thanks for helping! 

Yes, I can see an IPV6 address and ping6 the default gateway. I can also see the route table.
Do you want me to provide any specific information?

**Comment by coolhva** [comment]
can you ping the dns server from the USG?

``unifiadmin@HVA-USG-GW:~$ ping6 2606:4700:4700::1111
PING 2606:4700:4700::1111(2606:4700:4700::1111) 56 data bytes
64 bytes from 2606:4700:4700::1111: icmp_seq=1 ttl=61 time=4.20 ms
64 bytes from 2606:4700:4700::1111: icmp_seq=2 ttl=61 time=4.11 ms
64 bytes from 2606:4700:4700::1111: icmp_seq=3 ttl=61 time=4.10 ms
64 bytes from 2606:4700:4700::1111: icmp_seq=4 ttl=61 time=4.22 ms``

**Comment by eliosfederico** [comment]
No, look the screenshot above. It will try but it won't receive anything and I have to stop it.

`eliosfederico@Router:~$ ping6 2606:4700:4700::1111`
`PING 2606:4700:4700::1111(2606:4700:4700::1111) 56 data bytes`
`^C`
`--- 2606:4700:4700::1111 ping statistics ---`
`74 packets transmitted, 0 received, 100% packet loss, time 73005ms`

**Comment by coolhva** [comment]
can you post the route table from the usg?

```
netstat -r -6
```

**Comment by eliosfederico** [comment]
![rr](https://user-images.githubusercontent.com/725955/72740188-7b26bb80-3ba5-11ea-93da-e67bdbb4fd10.JPG)

**Comment by coolhva** [comment]
I can see a different output on my route table:
```
::/0                           ::                         U    1024 25     0 pppoe2
```
Your next hop is weird, did you configure IPv6 on the WAN network in the controller (can you post a screenshot of your WAN network settings in your controller)?

What firmware version is the USG and controller on?

**Comment by eliosfederico** [comment]
When I provisioned the config I had IPV6 configured on the GUI but later disabled it, see screenshot.
I also had IPV6 enabled in the LAN (on the GUI) but it is now also disabled (GUI won't let you enable IPV6 if the WAN doesn't have IPV6).  
USG is 4.4.44.5213871 and controller 5.12.35.0.

![wan](https://user-images.githubusercontent.com/725955/72740774-a52cad80-3ba6-11ea-9849-7ff7132c7a3e.JPG)

![lan](https://user-images.githubusercontent.com/725955/72740806-b5dd2380-3ba6-11ea-8f92-6edd6f1a8b06.JPG)

**Comment by coolhva** [comment]
can you clear the vlan / dns servers on the WAN side and hit save and reprovision, reboot usg and check the route table / ping again?

**Comment by eliosfederico** [comment]
Done. As soon as the USG was online I went to check on ipv6-test.com and it was working but one moment later no IPV6 again and no ping from the USG.

![route2](https://user-images.githubusercontent.com/725955/72741641-56801300-3ba8-11ea-9952-e606cc2fcca3.JPG)

**Comment by coolhva** [comment]
if you check the route table again, did it change the next hop of the default route (to the fe80 address, or is it still ::).

**Comment by coolhva** [comment]
I've seen that you have a usg pro, can you post the contents of the dhcp6.sh in /config/scripts/post-config.d/ ?

**Comment by eliosfederico** [comment]
`#!/bin/vbash

readonly logFile="/var/log/postprovision.log"

source /opt/vyatta/etc/functions/script-template

configure > ${logFile}

delete system task-scheduler task postprovision >> ${logFile}
set interfaces ethernet eth2 vif 6 pppoe 2 dhcpv6-pd no-dns >> ${logFile}
set interfaces ethernet eth2 vif 6 pppoe 2 dhcpv6-pd pd 0 interface eth0 prefix-id :1 >> ${logFile}
set interfaces ethernet eth2 vif 6 pppoe 2 dhcpv6-pd pd 0 interface eth0 service slaac >> ${logFile}
set interfaces ethernet eth2 vif 6 pppoe 2 dhcpv6-pd pd 0 prefix-length /48 >> ${logFile}
set interfaces ethernet eth2 vif 6 pppoe 2 dhcpv6-pd rapid-commit disable >> ${logFile}
commit
exit`

**Comment by eliosfederico** [comment]
The table changed again now (after the two minutes) and it looks like the one before to me:

![route3](https://user-images.githubusercontent.com/725955/72742273-ac08ef80-3ba9-11ea-849c-29cf51f88558.JPG)

**Comment by coolhva** [comment]
can you remove the dhcp6.sh from the usg, reboot and see if the USG has and keeps IPv6? If that is the case then there is an old IPv6 configuration sent from the controller which is interfering with your setup.

**Comment by eliosfederico** [comment]
USG is up and running and just like before IPV6 works only in the 30 seconds after it has booted.
This is the table at the moment:

![route4](https://user-images.githubusercontent.com/725955/72743012-1e2e0400-3bab-11ea-91f5-99952241682d.JPG)

**Comment by coolhva** [comment]
I  have not seen this behaviour in the past and I am not aware what can caused this. My advise is to:

1. reset USG to factory defaults
2. configure your WAN side in the controller with IPv4 AND IPv6 and make it work
3. remove WAN settings (disable ipv6 and set it to dhcp)
4. put my scripts in place (edited with the correct interfaces)
5. see it it works.

so as you can see it is quite some work but there is something messing up your ipv6 configuration and a the steps above hopefully can resolve this.

**Comment by eliosfederico** [comment]
So now I proceed to use your config and files?

**Comment by eliosfederico** [comment]
Reconfigured the USG with your files and same problem. IPV6 works for 30 seconds to 1 minute after boot, then stops. This is funnily enough the same behaviour when configuring IPV6 from the GUI, without using the config that I posted on my last message. The config I have it from this website [https://gathering.tweakers.net/forum/list_messages/1938584](url) and I used it when I had bridged IPTV.

**Comment by eliosfederico** [comment]
I added `"dhcpv6-pd": {
                                    "prefix-only": "''"
                                },`

And it works now!

**Comment by coolhva** [comment]
Good to hear. I still think this fixed a leftover of your old config. All the other people did not need this in the config to make it work.

But if it works, don’t fix it!
