### ISSUE TITLE
Postprovision script

### ISSUE THREAD

**Issue by eliosfederico** [coolhva/usg-kpn-ftth#14]
Is it normal that when the USG provisions when, for example, changing a firewall setting in the controller, that the IPV6 goes down for 2 minutes waiting for the script to run?

I thought it was just needed at boot, but maybe I was wrong.

**Comment by coolhva** [comment]
When you change a setting at the controller it depends on the change if the USG is provisioned or not. Maybe, in the latest version, we can incorporate IPv6 in the JSON and not in a script. There was a bug however which did not allow the length of configuration lines.
