### ISSUE TITLE
IPv6 via JSON

### ISSUE THREAD

**Issue by DandyDev** [coolhva/usg-kpn-ftth#16]
First of all: thanks for sharing this. Super useful!

In your instructions, you mention that due to a bug, we cannot configure IPv6 properly via JSON. It seems, however, that [the bug was fixed](https://community.ui.com/questions/Configuration-commit-errors-IPv6-PPPoE-invalid-prefix-ID-value-validation-failed-etc-/b4fee8c4-58c1-43ba-8019-5c1ea78fabe5#answer/6ec6a407-1c63-42f3-a600-c371e4b69bac).

Does that mean we can get rid of the `dhcp6.sh` now and incorporate IPv6 config in the JSON file? If so, how do we go about that?

**Comment by coolhva** [comment]
In theory yes, but for backwards compatibility I will keep it for now.
If you want to remove it yourself please run the config dump command and copy the relevant options to the json yourself.

https://help.ubnt.com/hc/en-us/articles/215458888-UniFi-USG-Advanced-Configuration

#mca-ctrl -t dump-cfg
