### ISSUE TITLE
IPTV hangs

### ISSUE THREAD

**Issue by kdesigns** [coolhva/usg-kpn-ftth#19]
I have followed all the steps and all works except for that the IPTV hangs after a couple of seconds. It then starts again after a couple of seconds, and then stops again.

I have to add that my KPN 4k (latest model) set-top box is plugged into --> UniFi Switch 8 --> which is connected to a UniFi Switch 24 --> plugged in to the USG.

At the moment I have no custom VLAN's configured. Everything is still default except for your scripts.

I have internet fine, a couple of UniFi AP-AC-Pro's, Apple TV's, Samsung TV's, Sonos, security cams in the network.

Do I have to configure the switches? Anything else?

Thanks so much for your effort!

**Comment by kloknibor** [comment]
For me it was running fine for a while. But today after a commit gone wrong I have done a factory reset and re-provisioned the USG and reuploaded the 2 .sh files. After that my tv hangs and sometimes gives the message I should swap channels to get it working as well.

I can either wait for a very long time or run "restart igmp-proxy" to get tv working again.

**Comment by coolhva** [comment]
Please try firmware version 4.4.50.5272448 as the latest version does give problems.

**Comment by coolhva** [comment]
Another option is to put IPTV in a different VLAN (please adjust the IGMP configuration in the JSON accordingly)

**Comment by immert20** [comment]
Same problem here, it worked fine for me from 17-07-2020 until 31-07-2020. Now I get the same problemen. I have changed nothing and I got version  4.4.51 installed. Yesterday I downgrade the USG3 to  4.4.50 but that doesn't matter.

**Comment by kloknibor** [comment]
> > Another option is to put IPTV in a different VLAN (please adjust the IGMP configuration in the JSON accordingly)
> 
> How to do this? I also found this solution and might try it later this week : [basmeerman/unifi-usg-kpn#34](https://github.com/basmeerman/unifi-usg-kpn/issues/34)

I tried to add the restart igmp script to the gateway.json but now instead of a message saying you need to switch channels it just freezes completely

**Comment by DutchEllie** [comment]
As this issue hasn't yet been closed, I am experiencing the same issue. I followed the exact procedure from the guide. The ip route information is fine, the wan config is fine, the whole thing works. For a while. The igmp-proxy seems to crash for me every so often. Not totally sure how often it crashes, as I've only had this since yesterday night and this morning, but it appears that the igmp-proxy crashed overnight. Running a simple "restart igmp-proxy" fixed the problem immediately.
My USG is on firmware version 4.4.51.5287926
My USW is on firmware version 5.43.18.12487
Any ideas why that would be?

**Comment by coolhva** [comment]
This seems to happen to multiple people. Some blame it on the Firmware, 4.4.50 seems to be more stable, others blame it on other IGMP traffic. You can try to use my VLAN guide to put the IPTV box on a different VLAN and disable IGMP proxy on the LAN.

**Comment by NewOakley** [comment]
> Please try firmware version 4.4.50.5272448 as the latest version does give problems.

This firmware for the USG is for my experience also the best. Does the firmware for the controller effect! Which controller version has the best experience if I may ask?
