### ISSUE TITLE
IPv6 DNS question

### ISSUE THREAD

**Issue by s1l3ns** [coolhva/usg-kpn-ftth#2]
First of all, thanks for sharing your USG configuration. 

I was going over the config and noticed that you're using Cloudflares IPv6 name-servers:
```
                        "name-server": [
                        	"2606:4700:4700::1111",
                        	"2606:4700:4700::1001"
```
I'm assuming this is just personal preference, but curious to know why you decided to go with this rather than KPNs name-servers:

```
2a02:a47f:e000::53 
2a02:a47f:e000::54 
```

**Comment by coolhva** [comment]
Your assumption is correct, I find that cloudflare DNS servers are fast and they do not filter (or replace NXDOMAIN). If you want to use your own DNS servers you should replace those.

**Comment by SeBsZ** [comment]
Apologies for writing in this ticket, but I noticed too that my DNS servers are set to cloudflare. Is it no longer possible to configure these using the Unifi Controller Web UI? Why does your KPN config override them? In any case thanks for your work, it works perfectly.
