### ISSUE TITLE
VPN L2TP not connecting

### ISSUE THREAD

**Issue by stehof2** [coolhva/usg-kpn-ftth#25]
Hi,

First of all, thanks for this manual how to configure a USG with KPN, I'm using a USG 4 Pro so I had to change the ethX interfaces by the correct number and it works like a charm for internet and IPTV!

I'm only stuck on one part now, that's VPN L2TP, I placed the .sh file like mentioned, I followed a YT video (https://www.youtube.com/watch?v=ote3Zv0XdyU) how to setup the radius config, but no luck so far.

So my eth0 is LAN and eth2 is WAN for clarification.
If I ssh into my use, configure and command: "show vpn" this is the output:

ipsec {
     ipsec-interfaces {
         interface eth2.6
+        interface pppoe2
     }
     nat-networks {
         allowed-network 0.0.0.0/0 {
         }
     }
     nat-traversal enable
 }
 l2tp {
     remote-access {
         authentication {
             mode radius
             radius-server 192.168.0.1 {
                 key XXXXXXXXX
                 port 1812
             }
         }
         client-ip-pool {
             start 192.168.10.1
             stop 192.168.10.6
         }
         dhcp-interface eth2.6
         dns-servers {
             server-1 192.168.0.1
         }
         ipsec-settings {
             authentication {
                 mode pre-shared-secret
                 pre-shared-secret XXXXXXXXX
             }
             ike-lifetime 3600
         }
+        outside-address 0.0.0.0
     }
 }

When I try to connect using a L2TP VPN profile from my iPhone, I've set the server to my public 83.x.x.x address, filled out the account, password and secret field, then try to connect but I get an error: "The L2TP-VPN server did not respond.". Se he doesn't seem to reach the server, what am I doing wrong?

**Comment by xHuubx** [comment]
Hello stefhof2, I use a USG, and after I saw:  https://github.com/basmeerman/unifi-usg-kpn/issues/7

I used the suggested command on mu USG:

`configure
set vpn ipsec ipsec-interfaces interface pppoe2
delete vpn l2tp remote-access dhcp-interface eth0
set vpn l2tp remote-access outside-address 0.0.0.0
commit
save`

Then it worked. I than added this in the startup script so after a reboot it would be set again..
Not sure this is the same for USG4, but you can always try right ?

**Comment by stehof2** [comment]
> Not sure this is the same for USG4, but you can always try right ?

Hi Huub,
Thanks for thinking with me, I used/placed the setvpn.sh script indeed, in this script the same command are set. The only difference for me is that the wan interface is on eth2 where the wan interface on use3 is on eth0, so this is the only thing I edited in the code.
How does your L2TP config looks like?

**Comment by xHuubx** [comment]
You mean the L2TP config on my iPhone?

**Comment by xHuubx** [comment]
![7D1537B6-0017-4541-A8DC-DC6D85F5C467](https://user-images.githubusercontent.com/16132415/100276827-6f90e780-2f62-11eb-80eb-7ac08907f66e.jpeg)

**Comment by stehof2** [comment]
Ah ok, yea I've the same settings, did you do anything special on the Unifi controller when you configured the L2TP VPN? For example, did you made port forwarding or something?

**Comment by xHuubx** [comment]
Have a look at this https://youtu.be/LGp8LBcg4fE

**Comment by stehof2** [comment]
Hmmm I did exactly the same thing as shown in the video.
Now I'm trying to troubleshoot what goes wrong, apparently the VPN connection request is reaching the radius server but won't connect in the end, when I command: "**show vpn log tail**" to see what happens when I connect my VPN, this is the output:

```
Nov 25 22:35:08 03[IKE] <6> 77.63.72.137 is initiating a Main Mode IKE_SA
Nov 25 22:35:09 06[IKE] <remote-access|6> IKE_SA remote-access[6] established between 86.X.X.X[86.X.X.X]...77.63.72.137[0.0.0.0]
Nov 25 22:35:10 08[IKE] <remote-access|6> CHILD_SA remote-access{6} established with SPIs cdb628c8_i 0fed2843_o and TS 86.X.X.X/32[udp/l2f] === 77.63.72.137/32[udp/63203] 
Nov 25 22:35:30 02[IKE] <remote-access|6> deleting IKE_SA remote-access[6] between 86.X.X.X[86.X.X.X]...77.63.72.137[0.0.0.0]
```

Any thought what goes wrong?

**Comment by xHuubx** [comment]
Did you check FW rules ?
Maybe recheck everything:
https://rowelldionicio.com/unifi-usg-configuring-remote-access-vpn/

**Comment by stehof2** [comment]
I checked it but I don't have any forward rule or firewall rule custom made, everything is default for now, I first want to get everything working before I start deny some connections in the firewall.

If I look at the instructions on the url, is the same thing I did so I really don't understand why it won't work...

**Comment by Palm92** [comment]
Any updates? I followed the instructions and everything is working except the VPN L2TP.

**Comment by stehof2** [comment]
> Any updates? I followed the instructions and everything is working except the VPN L2TP.

Sadly not, nothing yet, for me the same issue... if I have some time I want to find a good guide how to troubleshoot the configuration to see on what part the connection fails

**Comment by stehof2** [comment]
Btw, I also tried to get an answer from the community but no replies over there... https://community.ui.com/questions/VPN-L2TP-USG4-pro-wont-connect/c40c5341-6ef6-40bc-8823-9e17c2da723c

**Comment by Goz3rr** [comment]
I also ran into the same issue, after checking the log (`/var/log/postprovisionvpn.log`) it just had one line in it:
> Nothing to delete (the specified value does not exist)

Going into `configure` and running `show vpn` explains why: my `dhcp-interface` is set to `eth0.6`, and the script tries to delete `eth0`. If you try to add the `outside-address` without removing it, committing the config results in the following error:
> L2TP VPN configuration error: Only one of dhcp-interface and outside-address can be defined..

Which isn't logged because the `setvpn.sh` script does not pipe the output of configure. Simply replacing `eth0` with `eth0.6` in the script makes it delete the proper thing, and after running the script again my VPN works.

**Comment by stehof2** [comment]
> I also ran into the same issue, after checking the log (`/var/log/postprovisionvpn.log`) it just had one line in it:
> 
> > Nothing to delete (the specified value does not exist)
> 
> Going into `configure` and running `show vpn` explains why: my `dhcp-interface` is set to `eth0.6`, and the script tries to delete `eth0`. If you try to add the `outside-address` without removing it, committing the config results in the following error:
> 
> > L2TP VPN configuration error: Only one of dhcp-interface and outside-address can be defined..
> 
> Which isn't logged because the `setvpn.sh` script does not pipe the output of configure. Simply replacing `eth0` with `eth0.6` in the script makes it delete the proper thing, and after running the script again my VPN works.

Ah now you mentioned it, it makes sense indeed. I’m using a USG4 pro so my WAN is on eth2 so I had to change it to delete dhcp-interface from 2.6, after that’s changed and I rebooted it is finally working, thanks a lot.

Do you also know by change how to configure the USG so it will allow connecting to a web service that is behind a specific port?

For example, I’m using Openhab, the config page uses port 8080 and that’s working fine, but on the same IP the log viewer is behind 9001 and if I try to open it the page won’t load. Same thing for MotionEye, there default page is behind port 8765 so that one is also unavailable.

Do I’ve to great a Firewall rule to allow this or is there something else that will do the trick?

**Comment by Goz3rr** [comment]
I'm not sure, by default the VPN should have full access to the corporate network. There shouldn't be a reason that port 8080 works but the others don't.

I'm guessing you either have a firewall rule that is blocking those, in which case you'd need to remove that rule or add another that explicitly allows them, or there's something blocking it on your server, either a firewall or a configuration that only allows connections from the local subnet (i.e. your LAN is 192.168.0.x but the VPN clients get a 172.16.0.x IP)

**Comment by Palm92** [comment]
Still no luck.. 

my dhcp-interface is set to eth0 so the setvpn.sh script is oke.

When i try to connect the following happens:

show vpn log tail
Jan  1 12:58:13 11[IKE] <remote-access|12> IKE_SA remote-access[12] established between XX.XX.XX.XX[XX.XX.XX.XX]...192.168.1.97[192.168.1.97]
Jan  1 12:58:14 03[IKE] <remote-access|12> CHILD_SA remote-access{10} established with SPIs c0220d8a_i 08411400_o and TS XX.XX.XX.XX/32[udp/l2f] === 192.168.1.97/32[udp/53401] 
Jan  1 12:58:45 06[IKE] <remote-access|12> closing CHILD_SA remote-access{10} with SPIs c0220d8a_i (720 bytes) 08411400_o (224 bytes) and TS XX.XX.XX.XX/32[udp/l2f] === 192.168.1.97/32[udp/53401] 
Jan  1 12:58:45 01[IKE] <remote-access|12> deleting IKE_SA remote-access[12] between XX.XX.XX.XX[XX.XX.XX.XX]...192.168.1.97[192.168.1.97]
Jan  1 12:58:51 09[KNL] interface ppp1 deleted

**Comment by stehof2** [comment]
> I'm not sure, by default the VPN should have full access to the corporate network. There shouldn't be a reason that port 8080 works but the others don't.
> 
> I'm guessing you either have a firewall rule that is blocking those, in which case you'd need to remove that rule or add another that explicitly allows them, or there's something blocking it on your server, either a firewall or a configuration that only allows connections from the local subnet (i.e. your LAN is 192.168.0.x but the VPN clients get a 172.16.0.x IP)

Thanks, I found the issue, problem was that the devices with a different port had the old gateway fixed setup, by coincidence all the devices with 8080 already had the new gateway setup :)

**Comment by stehof2** [comment]
> Still no luck..
> 
> my dhcp-interface is set to eth0 so the setvpn.sh script is oke.
> 
> When i try to connect the following happens:
> 
> show vpn log tail
> Jan 1 13:16:58 03[IKE] <remote-access|14> IKE_SA remote-access[14] established between XX.XX.XX.XX[XX.XX.XX.XX]...31.161.221.135[0.0.0.0]
> Jan 1 13:16:59 07[IKE] <remote-access|14> CHILD_SA remote-access{12} established with SPIs c199dc2c_i 0cefe46a_o and TS XX.XX.XX.XX/32[udp/l2f] === 31.161.221.135/32[udp/51965]
> Jan 1 13:17:31 15[IKE] <remote-access|14> deleting IKE_SA remote-access[14] between XX.XX.XX.XX[XX.XX.XX.XX]...31.161.221.135[0.0.0.0]
> Jan 1 13:17:37 16[KNL] interface ppp1 deleted

Can you SSH into your USG, then type:
configure and press enter, then type show vpn and hit enter.
Can you paste the output here?

**Comment by Palm92** [comment]
> Can you SSH into your USG, then type:
> configure and press enter, then type show vpn and hit enter.
> Can you paste the output here?

Sure here is the configuration.

wpalm@USG:~$ configure
[edit]
wpalm@USG# show vpn
 ipsec {
     auto-firewall-nat-exclude disable
     ipsec-interfaces {
         interface eth0
         interface pppoe2
     }
     nat-networks {
         allowed-network 0.0.0.0/0 {
         }
     }
     nat-traversal enable
 }
 l2tp {
     remote-access {
         authentication {
             mode radius
             radius-server 192.168.1.1 {
                 key XXXX
                 port 1812
             }
         }
         client-ip-pool {
             start 192.168.3.1
             stop 192.168.3.254
         }
         dns-servers {
             server-1 192.168.1.1
         }
         idle 1800
         ipsec-settings {
             authentication {
                 mode pre-shared-secret
                 pre-shared-secret XXXX
             }
             ike-lifetime 3600
             lifetime 3600
         }
         outside-address 0.0.0.0
     }
 }
[edit]

**Comment by Palm92** [comment]
Oke het probleem is opgelost!

**De VPN connectie kwam niet tot stand door het volgende issue:**
https://community.ui.com/questions/USG-L2TP-issue-Authentication-Failed/17ecd602-5c95-4b35-8dd6-7fcacbfd892c#answer/88d832b6-3a68-490c-a3bb-d70b5fdbf29c

Het volgende script uitgevoerd:
mongo localhost:27117/ace
db.setting.remove({"key":"radius"})
exit

Vervolgens RADIUS server weer opnieuw aangezet en VPN kon gestart worden.

Issue kan gesloten worden.

**Comment by coolhva** [comment]
Awesome work everyone, thanks!
