### ISSUE TITLE
USG reboots/crashes at random times

### ISSUE THREAD

**Issue by DutchEllie** [coolhva/usg-kpn-ftth#26]
I already made a post about this on the UI forums [here](https://community.ui.com/questions/USG-3P-randomly-reboots/aa7e47a3-3f67-44a5-8086-402aa7d09ec8), but I wanted to ask here the same question. Basically my USG seems to restart at random times, mostly once a day but it has done it multiple times a day once or twice now. I've used your setup so that's why I thought it might be useful to ask you as well. As stated in the post on the UI forums, I am running firmware version 4.4.50, as 4.4.51 seemed too unstable for IPTV to work well.

**Comment by coolhva** [comment]
Did you try to use my new VLAN setup? 

https://www.vanachterberg.org/usg-kpn-ftth/posts/unifi-security-gateway-kpn-iptv-vlan/

Maybe something on your LAN may crash your IGMP proxy.

**Comment by DutchEllie** [comment]
I have not yet tried that, I'll try it later when I have the time

**Comment by DutchEllie** [comment]
I have introduced Vlans on the network, however not for the TV. I experimented with the new switch before adding it to the TV first. A shitty asus router that should be acting as only an access point is now separated from the network in its own vlan and no crash has occurred ever since.

I am beginning to think that that might have been the problem here. Whatever the problem was, I am not sure what caused it or what fixed it, but for now am hesitant to change it around too much.

Sorry for now to not have fixed the problem with a clear solution. If the problem ever returns I will segregate off the TV first thing

**Comment by DutchEllie** [comment]
So, I was wrong clearly. It restarted for no reason again. I moved the new switch and now have separated the iptv traffic to it's own vlan. The USG still likes to restart on it's own. I have tried to run 'show log tail' in ssh until it crashed but it showed nothing. There is also nothing in /var/log/messages around the time of crashing at all, only the default startup stuff. I will paste my /var/log/messages as an attachment 
[logmessages.txt](https://github.com/coolhva/usg-kpn-ftth/files/5758841/logmessages.txt)

furthermore here are the most recent times of crashes according to the controller:
31/12/2020 5:17 PM
31/12/2020 10:59 PM
1/1/2021 9:09 AM

The network setup is now as follows:
eth0.4 and eth0.6 as per your setup
eth1 is network 10.1.0.1/16
eth1.5 is network 10.0.0.1/16 (unused right now)
eth1.7 is network 10.7.0.1/16 (iptv network)

The igmp proxy is disabled on eth1 and 1.5 and set as role downstream for eth1.7. The port that goes to the living room is connected to a switch there that connects to both an already existing Amplifi setup and the tvbox. The incoming port there is set up as tagged for vlan 1 and 7. The port going to the amplifi is set up untagged vlan 1 and the tvbox is connected to an untagged vlan 7 port. Both work fine.

Another tvbox in a bedroom is connected directly to the USW and that switchport is set up with the IPTV profile.

If you need any more information just ask.

**Comment by coolhva** [comment]
Your log does not show the crash, only the normal startup. I highly recommend that you open a ticket with Ubiquity support and maybe also on their forum.

Did you also try to do a factory default on the USG and re-adopt it?

**Comment by DutchEllie** [comment]
I stated that the log doesn't include that crash, that's why it has been especially unhelpful. I have not opened a ticket with ubiquiti. I've read a long thread over there where they basically stated themselves that this might just be a hardware issue. That thread was from 2 years ago. Multiple people have said they RMA'd the device and received a working replacement. I will do the same. I have already requested an RMA for full replacement, so I will report back when that thing either does the same or works fine.
I am on mobile, forgive the links being unformatted. 

This is the thread where ubiquiti stated the hardware might be broken (it's not for the same exact device, but they're similar enough to neglect): https://community.ui.com/questions/USG-Pro-4-Restarting-every-2-days/61530cc9-a0a3-4a4d-b00b-b62997547658?page=44

And this is where multiple people RMA'd it with success:
https://community.ui.com/questions/USG-random-restart-no-log-messages/ef11cbb4-d530-4831-a970-25adc08e6090?page=6

Anyway, I best make sure to RMA it if it's a hardware issue, as its easier to deal with than warranty in my experience.

**Comment by DutchEllie** [comment]
Well, after getting a replacement the issue persists. I've let the device run for days without problems with its default configuration and when I finally found the time, replaced the experiabox yesterday. This morning it restarted again for no apparent reason.

/var/log/messages was completely full of martian source messages, it was too with the other USG, but forgot to mention I turned the logging for that off... Could that maybe be an issue?

**Comment by DutchEllie** [comment]
I finally got an error log that can be used! The log starts at the bottom and time flows up to the top, ending in "Rebooting in 60 seconds.." 
[2021-01-19.txt](https://github.com/coolhva/usg-kpn-ftth/files/5834535/2021-01-19.txt)

**Comment by coolhva** [comment]
Looks like you are not the only one: https://community.ui.com/questions/USG-Pro-Crashing-Daily/d9b53535-e2e5-4862-b166-299460e0aaa1

You must have something in your configuration that causes this. I suggest starting with minimal configuration (only internet, vlan 6 pppoe (user: kpn, pass: kpn) and see if that works.

**Comment by coolhva** [comment]
Unifi forum support will take it from here: https://community.ui.com/questions/USG-3P-kernel-panic-CPU-Unable-to-handle-kernel-paging-request-at-virtual-address-000000000000030c-/c0626420-e1b7-4218-b383-95f46a36dc29

this is not related to the configuration in this repo.
