### ISSUE TITLE
VPN disconnects after several minutes

### ISSUE THREAD

**Issue by rkops-bd** [coolhva/usg-kpn-ftth#28]
After reboot of my USG 4 Pro, the VPN connection can be setup.
After a minute or 5, the VPN will be disconnected, aand can't connect anymore.

After manually executing the setvpn.sh the connection can be made, but even after 5 minutes the connection will be terminated.

**Comment by coolhva** [comment]
is this with an android phone, seems that there are a lot of issues with L2TP and android phones. https://community.ui.com/questions/L2TP-VPN-to-USG-drops-out-after-90-seconds-with-Android-8-0-client/7d6b92d2-0cd9-4579-b8f8-dea6ae6ccf97

**Comment by coolhva** [comment]
Can you please try this command on the USG (through SSH) to see if this will fix the VPN connection:

```ip xfrm policy flush```

**Comment by rkops-bd** [comment]
> Can you please try this command on the USG (through SSH) to see if this will allow you create the VPN connection again:
> 
> `ip xfrm policy flush`

This won't work.
The issue occours on every OS (iOS, Windows, macOS)

**Comment by coolhva** [comment]
can you see what the configuration looks like after it stops working?

```shell
>configure
#show vpn
```

Do you see the remote-access dhcp-interface rule back in the configuration or do you still see the outside-address 0.0.0.0 in the config?

Maybe your USG will re-provision after 5 minutes and overrides the changes.

**Comment by coolhva** [comment]
Please re-open if there is still an issue
