### ISSUE TITLE
Usg pro no pppoe2

### ISSUE THREAD

**Issue by xthephreakx** [coolhva/usg-kpn-ftth#29]
Not sure if this is a bug or something I did wrong... 

I followed the page for my usg pro 4 changed the eth ports accordingly so it matches the pro and not de usg (which I didn’t do  before and put the pro in a provisioning loop *facepalm*) 

So with correct settings I provisioned the pro 

but when I run show interfaces 
It’s not showing the pppoe2 interface...
Also no internet access 
Rebooted multiple times 

Am I missing something?

@UniFiSecurityGatewayPRO:~$ show interfaces
Codes: S - State, L - Link, u - Up, D - Down, A - Admin Down
Interface    IP Address                        S/L  Description
---------    ----------                        ---  -----------
eth0         192.168.187.200/24                u/u  LAN
eth0.99      192.168.99.1/24                   u/u
eth0.107     192.168.107.1/24                  u/u
eth1         -                                 A/D
eth2         -                                 u/u  WAN
eth2.4       10.87.202.38/22                   u/u  IPTV
eth2.6       -                                 u/u
eth3         -                                 A/D
lo           127.0.0.1/8                       u/u
             ::1/128

Also i was an telfort user but was transferd to KPN last year due to takeover

**Comment by coolhva** [comment]
I need to see the json to see where it might go wrong. Can you attach it to your comment?

**Comment by xthephreakx** [comment]
i'm actually returning the Pro for a normal usg because its a bit of an overkill on my network. but here are the files. 

[config.gateway.json.txt](https://github.com/coolhva/usg-kpn-ftth/files/5868848/config.gateway.json.txt)
[setroutes.sh.txt](https://github.com/coolhva/usg-kpn-ftth/files/5868849/setroutes.sh.txt)

but if there are any fault i would like to know so i can use the file on the USG p3

**Comment by coolhva** [comment]
I cannot see why it would fail. I you get a USG3 then you can just use the files without any change.

**Comment by xthephreakx** [comment]
> I cannot see why it would fail. I you get a USG3 then you can just use the files without any change.

unfortunately with the USG3 same issue with the downloaded zip file.

@SecurityGateway:~$ show interfaces
Codes: S - State, L - Link, u - Up, D - Down, A - Admin Down
Interface    IP Address                        S/L  Description
---------    ----------                        ---  -----------
eth0         192.168.187.29/24                 u/u  WAN
eth0.4       -                                 u/u  IPTV
eth0.6       -                                 u/u
eth1         192.168.187.44/24                 u/u  LAN
eth1.99      192.168.99.1/24                   u/u
eth1.107     192.168.107.1/24                  u/u
eth2         -                                 A/D
lo           127.0.0.1/8                       u/u
             ::1/128

do i need to add something ?

**Comment by coolhva** [comment]
Do you have the WAN of the USG connected to the NTU? I see an intern address on your WAN interface, looks like it is connected to the Experia/Fritz-box

**Comment by xthephreakx** [comment]
my bad i send the wrong text *facepalm*

SecurityGateway:~$ show interfaces
Codes: S - State, L - Link, u - Up, D - Down, A - Admin Down
Interface    IP Address                        S/L  Description
---------    ----------                        ---  -----------
eth0         -                                 u/u  WAN
eth0.4       10.87.202.96/22                   u/u  IPTV
eth0.6       -                                 u/u
eth1         192.168.187.44/24                 u/u  LAN
eth1.99      192.168.99.1/24                   u/u
eth1.107     192.168.107.1/24                  u/u
eth2         -                                 A/D
lo           127.0.0.1/8                       u/u
             ::1/128
cable comes directly from the NTU to the WAN

**Comment by xthephreakx** [comment]
![image](https://user-images.githubusercontent.com/5319954/106028053-c7b3a980-60cb-11eb-9984-88d2d88b8107.jpeg)

![image](https://user-images.githubusercontent.com/5319954/106028416-32fd7b80-60cc-11eb-994d-ff697d335f90.jpeg)

**Comment by xthephreakx** [comment]
also noticed that i dont have the greyed out vlan 6 as in your screenshot the the wan network page

**Comment by xthephreakx** [comment]
Found another guide which was made specific for Telfort user. Which I tried which partially works because I have to use another vlan 34

See screenshot 
![image](https://user-images.githubusercontent.com/5319954/106361944-646e8500-6320-11eb-8b62-22efea932803.jpeg)

Unfortunately I don't have a internet connection available... so I'm still missing something
