### ISSUE TITLE
Brigde the voip vlan 7 to the LAN2/VOIP port

### ISSUE THREAD

**Issue by Crush3rX** [coolhva/usg-kpn-ftth#30]
Would it be possible to bridge the incomming VoIP VLAN to LAN2 (Or a VLAN on LAN1)? currently I use a switch between the NTU and the WAN to split the VLAN off to the experiabox, I am using the experiabox purely as a VoIP converter.

**Comment by coolhva** [comment]
It would be possible but I strongly advise to get a VOIP phone as a bridge will also hurt performance.

A commit with the VOIP bridge functionality: https://github.com/basmeerman/unifi-usg-kpn/pull/22/files#diff-497a00729741b899362b944369ae570151634e7bfee20b078453268766cb1431
