### ISSUE TITLE
Vlan setup not working as expected..

### ISSUE THREAD

**Issue by bvansluis** [coolhva/usg-kpn-ftth#31]
Hi Henk, I was able to complete the first tutorial and everything works! Thank you and the coffee is on its way. Now I want to work with vlan's, but I can't quite figure that out. I have the setup as follows:
NTU > USG->16P Unifi Switch -> Netgear GS105Ev2
That Netgear is in the living room. The KPN IPTV connect to the Netgear, among other things. The ports on the Netgear are as follows:
Port 1 -> Port 3 16P unifi switch
Port 2 -> KPN IPTV
Port 3 -> Sonos Boost
Port 4 -> TV
Port 5 -> Media Player

In addition, IGMP Snooping is enabled. I have performed the vlan tutorial and put port 3 on the switch on vlan661. Config uploaded and force provision done.

On the Netgear I have the following settings:
![netgear1](https://user-images.githubusercontent.com/46501529/106394663-01ebb680-63fe-11eb-86fc-a8e5af978326.png)
![netgear2](https://user-images.githubusercontent.com/46501529/106394666-0912c480-63fe-11eb-83f2-e0cf823d7953.png)
![netgear3](https://user-images.githubusercontent.com/46501529/106394670-0c0db500-63fe-11eb-9b26-ff4307c430f9.png)
![netgear4](https://user-images.githubusercontent.com/46501529/106394674-0dd77880-63fe-11eb-9502-554cfe70ae18.png)
![netgear5](https://user-images.githubusercontent.com/46501529/106394676-0fa13c00-63fe-11eb-8945-f1f7174ca460.png)

Then I connected the switch and turned everything back on. However, all devices connected to the Netgear now get a 192.168.3.xx address, whereas I expected only the KPN cabinet to get this and the rest will simply get the normal 192.168.2.xx address. Is this possible at all or did I make a mistake somewhere in the config on the Netgear? Should the tagged and untagged be the other way around? I hope you can see where the mistake is?

**Comment by coolhva** [comment]
Did you create a new port profile in the unifi controller which has the native network set to LAN and the IPTV vlan as tagged network selected? This port profile should be attached to the port that leads to the Netgear switch.

**Comment by bvansluis** [comment]
I think I have indeed missed this step:
![image](https://user-images.githubusercontent.com/46501529/106401103-99fb9700-6422-11eb-8fa0-c17016fe05ca.png)
I will give it a go tomorrow and keep you posted! Thanks for the prompt reply

**Comment by bvansluis** [comment]
@coolhva, I have reconfigured everything and it was better, but not OK. For full reference, this is my setup:
![image](https://user-images.githubusercontent.com/46501529/106521013-e657dd00-64dd-11eb-865f-b5fcd67db132.png)
I created the Port Profile and changed the Profile on Port 3 of the 16P Switch. Updated the Netgear Switch with the proper settings en restarted everything. I could see the KPN IPTV box getting a 192.168.3.x ipaddress while the other devices remained in the 192.168.2.x range. 

However the TV didn't work. After a couple of stutters I got the famous stb-nmc-400 error code. Whatever I tried after, it didn't matter. I did saw some strange behaviour. The KPN box got linked to Port 4 on the 8P switch which is upstairs. This switch is connected via port #7 on the 16P switch. Also, there is a netgear switch with a KPN IPTV connected. I change the Port Profile on the #7Port to Lan (instead of all) and then the KPN IPTV was back to the switch downstairs. 

So after a while I reverted everything back to the Non Vlan setup and now everything is working again. I would love to get this setup to work in my home, so any help us much appreciated!

**Comment by coolhva** [comment]
Start small, get one setup box to work first. First get the vlan json on the USG and restart the USG. Then add the port profile on the USG switch and configure the netgear. Connect your laptop/pc to it and check if you get the correct IP (in the 661 VLAN). Then connect your IPTV box to it and see if it gets the correct IP. If you get an error on the setup box check if igmp is running (run, with SSH, "restart igmp-proxy" on the USG).

**Comment by coolhva** [comment]
@bvansluis did you try to add the VLAN to one of your IPTV boxes yet?

**Comment by bvansluis** [comment]
Hi @coolhva, I haven't found the time to test it yet. I hope to be able to do it soon. As far as I'm concerned you can close the issue for now.. I will report back if I encounter any issues.
