### ISSUE TITLE
VPN Connected, but no access to internal network

### ISSUE THREAD

**Issue by bvansluis** [coolhva/usg-kpn-ftth#32]
I have followed the steps in the guide (https://www.vanachterberg.org/usg-kpn-ftth/posts/unifi-security-gateway-kpn-l2tp-vpn/) and I have been able to establish a VPN connection via my iPhone. When I lookup my ip on my phone, it is indeed the IP adres of my provider. However, I'm not able to access any internal resources. I have checked and double checked all the settings and they are exactly as in the guide. Any tips how to troubleshoot and find a resolution?

**Comment by coolhva** [comment]
This may be caused by your firewall rules. Do you have any customer firewall rules in place?

**Comment by bvansluis** [comment]
I only have some firewall rules for xbox ports and a rule for the WireGuard VPN. Apart from that, I have created nothing. II had port 500 and 4500 in there once, but I have removed those because I read that could cause a conflict. 
![image](https://user-images.githubusercontent.com/46501529/107093644-e4f02280-6805-11eb-9df1-4d8452faaad8.png)


This is what is in the log (If have removed the IP-address:
04[NET] received packet: from xx.xx.xx.xxx[47365] to zz.zzz.zz.zz[500] (788 bytes)
04[ENC] parsed ID_PROT request 0 [ SA V V V V V V V V V V V V ]
04[IKE] received NAT-T (RFC 3947) vendor ID
04[IKE] received draft-ietf-ipsec-nat-t-ike vendor ID
04[IKE] received draft-ietf-ipsec-nat-t-ike-08 vendor ID
04[IKE] received draft-ietf-ipsec-nat-t-ike-07 vendor ID
04[IKE] received draft-ietf-ipsec-nat-t-ike-06 vendor ID
04[IKE] received draft-ietf-ipsec-nat-t-ike-05 vendor ID
04[IKE] received draft-ietf-ipsec-nat-t-ike-04 vendor ID
04[IKE] received draft-ietf-ipsec-nat-t-ike-03 vendor ID
04[IKE] received draft-ietf-ipsec-nat-t-ike-02 vendor ID
04[IKE] received draft-ietf-ipsec-nat-t-ike-02\n vendor ID
04[IKE] received FRAGMENTATION vendor ID
04[IKE] received DPD vendor ID
04[IKE] xx.xx.xx.xxx is initiating a Main Mode IKE_SA
04[ENC] generating ID_PROT response 0 [ SA V V V ]
04[NET] sending packet: from zz.zzz.zz.zz[500] to xx.xx.xx.xxx[47365] (136 bytes)
07[NET] received packet: from xx.xx.xx.xxx[47365] to zz.zzz.zz.zz[500] (356 bytes)
07[ENC] parsed ID_PROT request 0 [ KE No NAT-D NAT-D ]
07[IKE] local host is behind NAT, sending keep alives
07[IKE] remote host is behind NAT
07[ENC] generating ID_PROT response 0 [ KE No NAT-D NAT-D ]
07[NET] sending packet: from zz.zzz.zz.zz[500] to xx.xx.xx.xxx[47365] (372 bytes)
04[NET] received packet: from xx.xx.xx.xxx[47366] to zz.zzz.zz.zz[4500] (108 bytes)
04[ENC] parsed ID_PROT request 0 [ ID HASH N(INITIAL_CONTACT) ]
04[CFG] looking for pre-shared key peer configs matching zz.zzz.zz.zz...xx.xx.xx.xxx[0.0.0.0]
04[CFG] selected peer config "remote-access"
04[IKE] IKE_SA remote-access[5] established between zz.zzz.zz.zz[zz.zzz.zz.zz]...xx.xx.xx.xxx[0.0.0.0]
04[ENC] generating ID_PROT response 0 [ ID HASH ]
04[NET] sending packet: from zz.zzz.zz.zz[4500] to xx.xx.xx.xxx[47366] (76 bytes)
09[NET] received packet: from xx.xx.xx.xxx[47366] to zz.zzz.zz.zz[4500] (412 bytes)
09[ENC] parsed QUICK_MODE request 1320928553 [ HASH SA No ID ID NAT-OA NAT-OA ]
09[IKE] received 3600s lifetime, configured 0s
09[ENC] generating QUICK_MODE response 1320928553 [ HASH SA No ID ID NAT-OA NAT-OA ]
09[NET] sending packet: from zz.zzz.zz.zz[4500] to xx.xx.xx.xxx[47366] (204 bytes)
14[NET] received packet: from xx.xx.xx.xxx[47366] to zz.zzz.zz.zz[4500] (60 bytes)
14[ENC] parsed QUICK_MODE request 1320928553 [ HASH ]
14[IKE] CHILD_SA remote-access{5} established with SPIs cb5998c4_i 021b015c_o and TS zz.zzz.zz.zz/32[udp/l2f] === xx.xx.xx.xxx/32[udp/54614]
06[NET] received packet: from xx.xx.xx.xxx[47366] to zz.zzz.zz.zz[4500] (92 bytes)
06[ENC] parsed INFORMATIONAL_V1 request 1857403348 [ HASH D ]
06[IKE] received DELETE for IKE_SA remote-access[5]
06[IKE] deleting IKE_SA remote-access[5] between zz.zzz.zz.zz[zz.zzz.zz.zz]...xx.xx.xx.xxx[0.0.0.0]

Looking at this guide and the troubleshooting steps, it looks like an authentication error. 
https://help.ui.com/hc/en-us/articles/115005445768-UniFi-USG-UDM-Configuring-L2TP-Remote-Access-VPN
I have set the secrets and passwords to a very simple password and made them the same. But the same error remains. I always do a force provision after I have changed settings.

**Comment by bvansluis** [comment]
Hmm, interesting. I did some debugging with a friend and he asked me to run the following 5 lines:
configure
set vpn ipsec ipsec-interfaces interface pppoe2
delete vpn l2tp remote-access dhcp-interface eth0
set vpn l2tp remote-access outside-address 0.0.0.0
commit

After that, it worked! Not sure why, but maybe @coolhva you can tell. 
Every time after that when I made a change in the config (updated the pre shared key for example) I needed to run those lines again.

**Comment by coolhva** [comment]
![Here](https://www.vanachterberg.org/usg-kpn-ftth/posts/unifi-security-gateway-kpn-l2tp-vpn/) you find the guide to put ![setvpn.sh](https://github.com/coolhva/usg-kpn-ftth/blob/vpn/setvpn.sh) in ```/config/scripts/post-config.d``` . This is required because the controller thinks ETH0 is the WAN instead of the PPPoE2 interface.
