### ISSUE TITLE
How to use IPv4 internally only in order to prevent IPv6 client addresses from leaking while connected to VPN

### ISSUE THREAD

**Issue by sarvasana** [coolhva/usg-kpn-ftth#33]
Using this configuration, when connected to a VPN service, the client IPv6 address is leaked.
You can verify this yourself by connecting to such a provider and then visiting https://www.whatismyip.com/.

The IPv4 address will be the address from your VPN provider.
The IPv6 address is the address of your device.

How can I adapt this config to have an IPv6 address for just the USG and use IPv4 internally?
One way I can achieve this, is by disabling IPv6 on every client, but that is cumbersome.

In my setup a different server is running a VPN connection and this server is both the default gateway and DNS server.

**Comment by coolhva** [comment]
I recommend you create a VLAN/Network in the USG Controller and use that for IPv4 only traffic.
