### ISSUE TITLE
No connection

### ISSUE THREAD

**Issue by 00ihsan** [coolhva/usg-kpn-ftth#36]
After following the guide i get no internet and no wan showing up

![image](https://user-images.githubusercontent.com/57139073/111071643-6c9d1100-84d7-11eb-95cf-fe9dc9486558.jpeg)

**Comment by coolhva** [comment]
Seems the config.gateway.json is not picked up by the USG, which controller do you use?

**Comment by 00ihsan** [comment]
Just updated to 6.1.71 .

**Comment by coolhva** [comment]
Did you map /unifi in the docker container to a local directory on your NAS? Otherwise you do not have access to the sites default folder.

![image](https://user-images.githubusercontent.com/1774018/113191006-50ca9680-925d-11eb-899b-a388bfd392c0.png)

**Comment by 00ihsan** [comment]
Yes
![image](https://user-images.githubusercontent.com/57139073/113192003-891ea480-925e-11eb-94ba-008d32bc019e.png)

**Comment by 00ihsan** [comment]
Tried it today again. Now with controller 6.1.71 . also router update (4.4.55.5377096).the same issue.

show interfaces gives output: 
![IMG_8118](https://user-images.githubusercontent.com/57139073/114277266-c9361200-9a2a-11eb-85c7-be103fa30bc6.JPEG)

No connection as before.

**Comment by coolhva** [comment]
so the config.gateway.json is not being picked up. Maybe we could do a remote troubleshoot session to see if we can fix this together? If so please contact me at henk [at] vanachterberg.org

**Comment by 00ihsan** [comment]
Thanks to @coolhva everything works! I even learned a few new things!
