### ISSUE TITLE
Question: USG provisioning failing with error "MTU must be least than or equal to parent interface"

### ISSUE THREAD

**Issue by proddy** [coolhva/usg-kpn-ftth#37]
Hi all - I'm coming from a previous config (https://github.com/basmeerman/unifi-usg-kpn) to this config as I wanted IPv6, and getting this error after triggering a provision on the USG (version 4.4.55.5377096):

```
Apr 19 21:01:31 USG mcad: mcad[3208]: ace_reporter.reporter_handle_response(): edgemax apply config failed (error code: 2)
Apr 19 21:01:31 USG mcad: mcad[3208]: ace_reporter.reporter_handle_response(): commit errors, {"DELETE": {"failure": "0", "success": "1"}, "SESSION_ID": "e33d853246028b366d5ab45579", "SET": {"error": {"interfaces ethernet eth0 vif 6 mtu 1508": "MTU must be least than or equal to parent interface MTU\n\nValue validation failed\n"}, "failure": "1", "success": "1"}}#012
```

Weird thing is that the MTU of `6` (1508) is less than the parent `eth0` (1512)

Any ideas?

**Comment by coolhva** [comment]
I reverted the commit, please re-download the zip file and retry again.

This is a bug of the USG/controller and people will need to apply the MTU change AFTER they applied the configuration first. I will work on workaround for this issue.

Please let me know if the new download works @proddy

**Comment by proddy** [comment]
Thanks, I'll test it tonight. So is the idea to try the new config file and then if it works manually adjust both the MTUs using the CLI, like ` set interfaces ethernet eth0 mtu 1512`  for example? Or will that not persist?

**Comment by coolhva** [comment]
So after the config without the mtu you should be able to use the one with the mtu. Could you please test this?

**Comment by proddy** [comment]
Without mtu it works, going back to the original config.gateway.json gives the same error 

`Apr 21 19:45:00 USG mcad: mcad[3205]: ace_reporter.reporter_handle_response(): commit errors, {"DELETE": {"failure": "0", "success": "1"}, "SESSION_ID": "8e71df6fa870b8807c925c409e", "SET": {"error": {"interfaces ethernet eth0 vif 6 mtu 1508": "MTU must be least than or equal to parent interface MTU\n\nValue validation failed\n"}, "failure": "1", "success": "1"}}#012`

**Comment by proddy** [comment]
@coolhva any idea how to get the MTU's fixed?

**Comment by coolhva** [comment]
Yes, a post config hook, just like I did for the VPN. 

I need to consolidate the VPN with this post config hook for MTU so we only have one, and it should adapt for VPN automatically so I can make it more simple.

But, this takes time.

For the time being, please set the mtu with ssh and configure command. First eth0, then eth0 vif 6. Then commit and apply the json with the mtu.

**Comment by coolhva** [comment]
@proddy https://github.com/coolhva/usg-kpn-ftth/tree/kpn-aio

Download the zip, put the kpn.sh in /config/scripts/post-config.d, make it executable.

Restart the USG and then do a force provisioning. Please check (cat /var/log/kpn.log) that it changed the MTU.

Let me know!

**Comment by proddy** [comment]
thanks! I did try using the adjusted config with the MTU's removed, and then adding them manually using the CLI like:
```sh
% configure
% set interfaces ethernet eth0 mtu 1512
% commit
```
but it didn't work.

So with this new branch, I'm still using the same config (with no MTU) and replacing `setroutes.sh` with `kpn.sh` ?

**Comment by coolhva** [comment]
Yes, please try!

**Comment by proddy** [comment]
I finally had a slot to test it (no wife or kids hogging the network), and used the latest kpn.sh from the master branch. And it works. nice job!

```
admin@USG:~$ cat /var/log/kpn.log
[kpn.sh] Executed at Mon May  3 17:49:39 CEST 2021
[kpn.sh] creating lock file at /config/scripts/post-config.d/kpn.lock
[kpn.sh] The file /etc/commit/post-hooks.d/set-kpn-hook.sh does not exists, creating hook now
[kpn.sh] MTU for eth0 not configured, adjusting config
[kpn.sh] Disconnecting pppoe2 before changing MTU
Bringing interface pppoe2 down...
[kpn.sh] Setting mtu for eth0 to 1512
[kpn.sh] Setting mtu for eth0 vif 6 to 1508
[kpn.sh] Commiting
[set-kpn-hook.sh] Executed at Mon May  3 17:49:58 CEST 2021
[set-kpn-hook.sh] Configuration changes have been commited, adding crontab for kpn.sh
[kpn.sh] Connecting pppoe2 after changing MTU
Bringing interface pppoe2 up...
[kpn.sh] removing lock file at /config/scripts/post-config.d/kpn.lock
[kpn.sh] Executed at Mon May  3 17:50:02 CEST 2021
[kpn.sh] creating lock file at /config/scripts/post-config.d/kpn.lock
[kpn.sh] KPN found in crontab, removing /etc/cron.d/kpn
[kpn.sh] removing lock file at /config/scripts/post-config.d/kpn.lock
[kpn.sh] Finished
```

It looks like the MTUs are set correctly too.

many thanks
