### ISSUE TITLE
USG restarts or connections drops when using XS4ALL zip

### ISSUE THREAD

**Issue by WyriHaximus** [coolhva/usg-kpn-ftth#44]
The zip works perfectly well, but after a few hours the USG rebooted once and then restarted the PPOE connection 20 minutes later. Dropping all traffic for 5 minutes each time.

**Comment by coolhva** [comment]
did you try to factory reset and do it again?

**Comment by WyriHaximus** [comment]
Didn't, will try that soon. Also switched to KPN in the mean time. But I kinda assume that shouldn't matter.

**Comment by coolhva** [comment]
it does as KPN and XS4ALL use a different IPv6 issue.

**Comment by WyriHaximus** [comment]
Tried the factory reset, applied the zip from the readme and 6 hours later the USG randomly rebooted.
