### ISSUE TITLE
Firstime excute issue with KPN.sh

### ISSUE THREAD

**Issue by oozeorb** [coolhva/usg-kpn-ftth#46]
Hi Coolvha,

Awesome work some feedback. 

First issue i had with firmware 4.4.56
Was error msg command line was;  /bin/vbash^M: bad interpreter: No such file or directory.

Solution run this command line;  sed -i -e 's/\r$//' kpn.sh

The second problem error is; no such file or directory /var/log/kpn.log
Made the file by hand and in /var/log/ and all was fine.

Again awesome work thank you

**Comment by coolhva** [comment]
Sounds like a file format issue, how did you copy the files to the USG?

**Comment by oozeorb** [comment]
Yeah think so i didnt change the kpn.sh file at all. and I copy it with winscp

and the other issue is just because the file is not there

**Comment by coolhva** [comment]
Interesting, I will close the issue for now as there are no other reports and you fixed it yourself. This message will stay here so if people search for it they will find it and we might reopen it.
