### ISSUE TITLE
vlan

### ISSUE THREAD

**Issue by westridaz** [coolhva/usg-kpn-ftth#49]
Hey your script works for my default lan the ipv6 part, clients are getting an ipv6 address.

But i have a few more vlan (iot,homelab).

How can i get ipv6 for this vlan? i tried
https://gist.github.com/coolhva/31d19f62c4b50d24f4ee428b8b359193

But my internet wont come online, if edited the eth1.10 part to match mine which is eth1.30.

If saved the json, reprovisioned and rebooted serveral times.

On a working config on the usg “ show interfaces” i see the ipv6 working on eth1, on the edited one theres no ipv6 at all and no internet.

**Comment by coolhva** [comment]
the problem is that you have to add pd 1 and put the WAN configuration for the additional interface there. per PD you can only get one /64.

**Comment by westridaz** [comment]
Im kinda lost wat to edit in the config file. i tried to get the extra interface to work with ipv6 but isnt working. 

Your config works fine with the default lan on 192.168.1.1 but i would like to have extra interface 192.168.5.1 to work with ipv6 also if possible.

Any help would really appreciated.
