### ISSUE TITLE
IPv6 address public

### ISSUE THREAD

**Issue by bolijndotme** [coolhva/usg-kpn-ftth#53]
Hi, 

I followed [your guide](https://www.vanachterberg.org/usg-kpn-ftth/posts/unifi-security-gateway-kpn-ftth-iptv-ipv6/) to set up the USG3 with KPN FTTH, including IPTV. This works great and both internet and TV work ! 

I noticed that when i go to whatismyip.com it shows my ipv6 address, but i expected ipv6 to only be used internally. I followed your guide for debugging ([link](https://www.vanachterberg.org/usg-kpn-ftth/posts/unifi-security-gateway-problemen-oplossen/)) and see i have two IPv6 subnets when running `show interfaces` while your printscreen only has one. 

Two questions : 

1. How to only use IPv6 internally ?
2. Is there something wrong in my config for having two IPv6 addresses ?  

<img width="648" alt="Schermafbeelding 2022-09-12 om 15 51 38" src="https://user-images.githubusercontent.com/43075336/189674385-9df8565a-cad3-44b5-8956-ccc40c2237ab.png">

Thank you for your efforts ! 
Michel

**Comment by coolhva** [comment]
IPv6 allows computers to communicate with each other directly again, just like how in the beginning of the internet every computer had a public IP address. The firewall decides who can access your devices. If you want to use IPv6 locally you should use the fd00::/8 range and assign it to your interfaces. But, if you want to access Ipv6 services on the internet you will need a public IPv6 address, there is no NAT anymore.

The first address is the configured address, which can be referenced by other devices, or used for SSH. The second address  is created automatically using the SLAAC protocol.

**Comment by bolijndotme** [comment]
Thank you for your quick reply ! Is there a way to disable IPv6 ?

**Comment by coolhva** [comment]
Yes, you can edit the json config and remove the pd section from the wan interface. But why would you want to do that?

**Comment by bolijndotme** [comment]
I have several services (such as Wireguard and Pi-hole) running in my network and this was working fine, but since i'm using your script i have DNS errors. When i type `nslookup www.google.com 1.1.1.1` from any subnet it says `;; connection timed out; no servers could be reached`. I also removed the nameservers and radvd-options (like suggested in [this](https://github.com/coolhva/usg-kpn-ftth/issues/35) ticket), but it didn't work for me. 

So i want to see if the problem is fixed when i disable IPv6, so that i am sure the issue is not anything else.

you commented:
> remove the pd section from the wan interface

By this you mean to remove the following code block ? 
```
"pd": {
    "0": {
        "interface": {
            "eth1": {
                "host-address": "::1",
                "prefix-id": ":1",
                "service": "slaac"
            }
        },
        "prefix-length": "/48"
    }
}
```
