### ISSUE TITLE
Support for new Cloud Gateway Ultra

### ISSUE THREAD

**Issue by hapklaar** [coolhva/usg-kpn-ftth#57]
A bit premature, as [it](https://ui.com/cloud-gateways/ultra) has only just been released, but wondering if this can/will also be supported on this new device.

**Comment by proddy** [comment]
And the Gateway Max (UXG-Max) which was announced today!

**Comment by hapklaar** [comment]
Working with https://github.com/fabianishere/udm-iptv

**Comment by proddy** [comment]
thanks for sharing that link @hapklaar - I've ordered a UXG-Max to replace my old USG and will try it out
