### ISSUE TITLE
MTU issue

### ISSUE THREAD

**Issue by florisrobbemont** [coolhva/usg-kpn-ftth#7]
Hi,

First of all, thanks for the config files and scripts. I was used KPN in bridge mode instead of routed, and it stopped working yesterday.

When I try to upload your config to my USG, I get the following error:
{"DELETE":{"failure":"0","success":"1"},"SESSION_ID":"fb5867358399afc498daefc55d","SET":{"error":{"interfaces ethernet eth0 vif 6 mtu 1508":"MTU must be least than or equal to parent interface MTU\n\nValue validation failed\n"},"failure":"1","success":"1"}}

This is quite strange as all the config appears to be correct. I'm using the latest version of the controller and USG firmware.

Have you even encountered this before?

Thnx

**Comment by vincentbitter** [comment]
Had the same issue when I tried to deploy the first time. This is what I did to make the error go away:
1. Removed (corrupted) the gateway.config.json
2. Adopted the USG 3P
3. Changed back the gateway.config.json
4. Provisioned the USG 3P again

Doesn't feel like a nice solution, but it might help to reproduce/analyse/fix this issue.

**Comment by florisrobbemont** [comment]
Hi Vincent,

Should I then first forget the USG in the controller?

I must say that at the moment everything is running perfectly without the modified MTU’s.
I have a 500Mbit connection and my throughput is 60MBps. During heavy downloads the CPU of the USG doesn’t go above 5%. 

I’m feeling this change might not be neccesary for me?

**Comment by coolhva** [comment]
The MTU is just an optimization feature. It is not required. With more and more IPv6 coming, MTU/MSS sensing will stop fragmenting anyway.
