### ISSUE TITLE
Error 651 because 'routes' is not working

### ISSUE THREAD

**Issue by vincentbitter** [coolhva/usg-kpn-ftth#8]
I had this strange issue: after upgrading my Unifi Controller and Switch firmware this weekend, IPTV stopped working. When I restarted the USG 3P, it didn't came up anymore, so I had no other choice than resetting it. 

Now I am not sure whether I used the solution on this repo completely before. Since it looks really clean and stable, I wanted to implement it completely. Now after setting up all the files, IPTV still didn't work. Appearently I removed the software from Arris and had to download/install it again. However, this didn't succeed, because after the TV showed 'configuration activated', it gave an exception dialog with Error 651.

No matter what I did, I couldn't get it to work with the routes file. I finally excluded the setroutes.sh script and replaced it with [Bas Meerman](https://github.com/basmeerman/unifi-usg-kpn)'s solution. This works fine, so now I do have IPTV and IPv6 working smootly, but it's not the way I want it to work.

Two questions:
1. Why should you manually upload the routes file? If I am correct, that's the one setroutes.sh should create.
2. Is there anyone experiencing the same issue? Or have a clue how to fix it?

**Comment by coolhva** [comment]
the setroutes.sh in this solution will make sure that the DHCP static route extension is configured on the USG (which is not by default). KPN sends a classless static route to its IPTV platform in the DHCP Answer. To allow the USG to process this static route we need to create a script which executes as a DHCP exit hook which, when ran, will create a static route to the IPTV platform.

The reason I use the DHCP Exit hook (RFC3442) is that when KPN changes anything on their end it will be picked up by the USG automatically. In the troubleshooting post on tweakers you can see that I talk about looking if the route is present after two minutes after logging in. 

Another person has experienced Error 651 and they did the following:

1. turn off Arris Setup box
2. turn of (unifi) switch(es)
3. restart USG, login with SSH and check if the IPTV route is present
4. power on Unifi Switch
5. power on arris

and it started to work.

**Comment by vincentbitter** [comment]
Okay, that’s something I could try (probably next time I’m having trouble). This however does not answer my question if it is needed to upload the routes file itself, since setroutes.sh creates it too.

**Comment by coolhva** [comment]
Technically the answer is no. It will speed up the installation if the file is present. The reason setroutes is in the solution is that after a firmware update the routes file is no longer present in the correct location.

Did you find the troubleshooting post at tweakers? (Link is in the reader)

**Comment by vincentbitter** [comment]
That's a clear answer, thank you!
I found the post at tweakers, really useful information! Thanks again!
