### ISSUE TITLE
Missing  igmp-proxy.example.json  

### ISSUE THREAD

**Issue by davetin** [coolhva/usg-kpn-ftth#9]
Dear Coolhva,

Is it possible that the  igmp-proxy.example.json is missing?
I am unable to find it.
Thank you very much for your time and for the great information in regards to this topic!

yours sincerely,

Davetin

**Comment by coolhva** [comment]
Hi Davetin,

This file should be merged from the  https://github.com/slootjes/usg-kpn-ftth repository but it seems that it is not present. I will change the readme and remove this line as all the information is present in the readme. You can use the logic described in the readme to change your own configuration. If you need help please post the config in the tweakers.net forum https://gathering.tweakers.net/forum/list_messages/1883441/last and I will update it there.
